---
- name: update yum cache and install nginx
  yum:
    name: nginx
    state: latest
    update_cache: yes

- name: index.html copy
  template: src=/home/secadmin/index.html dest=/usr/share/nginx/html/index.html

- name: updated.html copy
  template: src=/home/secadmin/updated.html dest=/usr/share/nginx/html/index.html
  notify:
    - Restart Nginx
