---
- name: Capture facts from managed hosts
  hosts: INH
  remote_user: secadmin
  become: false
  gather_facts: yes
  
  tasks:
    - name: Save facts to a local file
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "/ansout1/facts/facts_{{ ansible_hostname }}_{{ ansible_date_time.date }}.json"
      delegate_to: localhost

