---
- name: Check and Install sar package
  hosts: REACHABLE
  tasks:
    - name: sar package present
      yum: 
        name: sysstat
        state: present
    - name: sar is started
      service:
        name: sysstat
        state: started
        enabled: true
